# Generated by Django 5.0.7 on 2024-07-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Verify_Contribution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='captcha_score',
        ),
    ]
