# Generated by Django 5.0.7 on 2024-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('not_seen', 'Not Seen'), ('seen', 'Seen'), ('action_taken', 'Action Taken'), ('solved', 'Solved')], default='not_seen', max_length=60),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('Sewage & Drainage', 'Sewage & Drainage'), ('Waste Management', 'Waste Management'), ('Public Transport', 'Public Transport'), ('Public Health Services', 'Public Health Services'), ('Education and Cultural', 'Education and Cultral'), ('Services', 'Services'), ('Water Treatment and Supplies', 'Water Treatment and Supplies')], max_length=60),
        ),
        migrations.AlterField(
            model_name='problem',
            name='seriousness',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=60),
        ),
    ]
