# Generated by Django 5.0.7 on 2024-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_problem_status_alter_problem_problem_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('condition', models.CharField(max_length=255)),
                ('last_maintenance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BedsInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('available', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('last_checked', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='O2Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('capacity_liters', models.IntegerField()),
                ('available', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('last_checked', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
