# Generated by Django 5.0.7 on 2024-07-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Excavator', 'Excavator'), ('Bulldozer', 'Bulldozer'), ('Garbage Truck', 'Garbage Truck'), ('Bus', 'Bus'), ('Other', 'Other')], max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=100)),
                ('last_known_location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_history', models.JSONField(blank=True, null=True)),
                ('operational_status', models.CharField(choices=[('Operational', 'Operational'), ('Under Repair', 'Under Repair'), ('Decommissioned', 'Decommissioned')], default='Operational', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Excavator', 'Excavator'), ('Bulldozer', 'Bulldozer'), ('Garbage Truck', 'Garbage Truck'), ('Bus', 'Bus')], max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('last_service_date', models.DateField()),
                ('next_service_due', models.DateField()),
            ],
        ),
    ]
