# Generated by Django 5.0.7 on 2024-07-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Excavator', 'Excavator'), ('Bulldozer', 'Bulldozer'), ('Garbage Truck', 'Garbage Truck'), ('Bus', 'Bus')], max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('last_service_date', models.DateField()),
                ('next_service_due', models.DateField()),
            ],
        ),
    ]
