# Generated by Django 5.0.7 on 2024-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
