# Generated by Django 5.0.7 on 2024-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery', models.CharField(max_length=100)),
                ('hours_of_operation', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=1)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
